[phases.setup]
nixPkgs = [
  "...",
  "curl",
  "pkg-config",
  "zlib",
  "zlib.dev",
  "libffi",
  "libffi.dev",
  "openssl",
  "openssl.dev",
  "freetype",
  "freetype.dev"
]

[phases.install]
cmds = [
  'curl -O https://bootstrap.pypa.io/get-pip.py',  
  'python3.12 get-pip.py',
  "pip install --upgrade pip",
  "pip install -r requirements-linux.txt"
]

[phases.start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
