[phases.setup]
nixPkgs = [
  "...",
  "curl",
  "pkg-config",
  "zlib",
  "zlib.dev",
  "libffi",
  "libffi.dev",
  "openssl",
  "openssl.dev",
  "freetype",
  "freetype.dev"
]

[phases.install]
cmds = [
  'python3.12 -m venv /app/venv',  # Create a virtual environment
  'source /app/venv/bin/activate',  # Activate the virtual environment
  'pip install --upgrade pip',  # Upgrade pip in the virtual environment
  'pip install -r requirements-linux.txt'  # Install dependencies
]

[phases.start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
