[phases.setup]
nixPkgs = [
  "python312Packages.pip",
  "gcc",
  "pkg-config",
  "zlib",
  "zlib.dev",
  "libffi",
  "libffi.dev",
  "openssl",
  "openssl.dev",
  "freetype",
  "freetype.dev"
]

[phases.install]
cmds = [
  "pip install --target=. -r requirements-linux.txt"
]

[phases.start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
