[phases.setup]
nixPkgs = [
  "python312Packages.pip"
]

[phases.install]
cmds = [
  "pip install --no-deps --target=. -r requirements-linux.txt"
]

[phases.start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
