[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "gcc",
  "pkg-config",
  "zlib",
  "zlib.dev",
  "libffi",
  "libffi.dev",
  "openssl",
  "openssl.dev",
  "freetype",
  "freetype.dev"
]

[phases.install]
# Upgrade pip and install your requirements
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements-linux.txt"
]

[phases.build]
# Optional: if you do any asset compilation, put it here
cmds = []

[phases.start]
# Start your FastAPI app with Uvicorn
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
