[setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "gcc",
  "pkg-config",
  "zlib",
  "zlib.dev",
  "libffi",
  "libffi.dev",
  "openssl",
  "openssl.dev",
  "freetype",
  "freetype.dev"
]

[install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements-linux.txt"
]

[build]
cmds = []

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
